// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: linkage.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkageGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Fuzzy  string `protobuf:"bytes,3,opt,name=fuzzy,proto3" json:"fuzzy,omitempty"`
}

func (x *LinkageGetReq) Reset() {
	*x = LinkageGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkageGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkageGetReq) ProtoMessage() {}

func (x *LinkageGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkageGetReq.ProtoReflect.Descriptor instead.
func (*LinkageGetReq) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{0}
}

func (x *LinkageGetReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LinkageGetReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LinkageGetReq) GetFuzzy() string {
	if x != nil {
		return x.Fuzzy
	}
	return ""
}

type LinkageGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*LinkageInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total   int64          `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *LinkageGetResp) Reset() {
	*x = LinkageGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkageGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkageGetResp) ProtoMessage() {}

func (x *LinkageGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkageGetResp.ProtoReflect.Descriptor instead.
func (*LinkageGetResp) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{1}
}

func (x *LinkageGetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkageGetResp) GetData() []*LinkageInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LinkageGetResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LinkageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Details    string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Createtime int64  `protobuf:"varint,4,opt,name=createtime,proto3" json:"createtime,omitempty"`
}

func (x *LinkageInfo) Reset() {
	*x = LinkageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkageInfo) ProtoMessage() {}

func (x *LinkageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkageInfo.ProtoReflect.Descriptor instead.
func (*LinkageInfo) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{2}
}

func (x *LinkageInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkageInfo) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *LinkageInfo) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

type LinkagePostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *LinkagePostReq) Reset() {
	*x = LinkagePostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkagePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkagePostReq) ProtoMessage() {}

func (x *LinkagePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkagePostReq.ProtoReflect.Descriptor instead.
func (*LinkagePostReq) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{3}
}

func (x *LinkagePostReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkagePostReq) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type LinkagePostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LinkagePostResp) Reset() {
	*x = LinkagePostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkagePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkagePostResp) ProtoMessage() {}

func (x *LinkagePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkagePostResp.ProtoReflect.Descriptor instead.
func (*LinkagePostResp) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{4}
}

func (x *LinkagePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LinkageDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LinkageDelReq) Reset() {
	*x = LinkageDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkageDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkageDelReq) ProtoMessage() {}

func (x *LinkageDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkageDelReq.ProtoReflect.Descriptor instead.
func (*LinkageDelReq) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{5}
}

func (x *LinkageDelReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LinkageDelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LinkageDelResp) Reset() {
	*x = LinkageDelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkageDelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkageDelResp) ProtoMessage() {}

func (x *LinkageDelResp) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkageDelResp.ProtoReflect.Descriptor instead.
func (*LinkageDelResp) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{6}
}

func (x *LinkageDelResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LinkagePutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Id      int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LinkagePutReq) Reset() {
	*x = LinkagePutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkagePutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkagePutReq) ProtoMessage() {}

func (x *LinkagePutReq) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkagePutReq.ProtoReflect.Descriptor instead.
func (*LinkagePutReq) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{7}
}

func (x *LinkagePutReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkagePutReq) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *LinkagePutReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LinkagePutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LinkagePutResp) Reset() {
	*x = LinkagePutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkagePutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkagePutResp) ProtoMessage() {}

func (x *LinkagePutResp) ProtoReflect() protoreflect.Message {
	mi := &file_linkage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkagePutResp.ProtoReflect.Descriptor instead.
func (*LinkagePutResp) Descriptor() ([]byte, []int) {
	return file_linkage_proto_rawDescGZIP(), []int{8}
}

func (x *LinkagePutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_linkage_proto protoreflect.FileDescriptor

var file_linkage_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x75, 0x7a, 0x7a, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x75, 0x7a, 0x7a, 0x79, 0x22, 0x68, 0x0a, 0x0e, 0x6c, 0x69, 0x6e,
	0x6b, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x22, 0x6b, 0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x22, 0x3e, 0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x22, 0x2b, 0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1f, 0x0a,
	0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a,
	0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x0d, 0x6c, 0x69,
	0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x6c, 0x69, 0x6e,
	0x6b, 0x61, 0x67, 0x65, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd9, 0x02, 0x0a, 0x07, 0x4c, 0x69, 0x6e, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x4e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x12,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x13, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x54, 0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x3a, 0x01, 0x2a, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x55, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x61,
	0x67, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x3d, 0x2a, 0x7d, 0x12, 0x51,
	0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x75, 0x74, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x50, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x61,
	0x67, 0x65, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x3a, 0x01, 0x2a, 0x1a, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67,
	0x65, 0x42, 0x1a, 0x5a, 0x18, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x6d, 0x79, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linkage_proto_rawDescOnce sync.Once
	file_linkage_proto_rawDescData = file_linkage_proto_rawDesc
)

func file_linkage_proto_rawDescGZIP() []byte {
	file_linkage_proto_rawDescOnce.Do(func() {
		file_linkage_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkage_proto_rawDescData)
	})
	return file_linkage_proto_rawDescData
}

var file_linkage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_linkage_proto_goTypes = []interface{}{
	(*LinkageGetReq)(nil),   // 0: proto.linkageGetReq
	(*LinkageGetResp)(nil),  // 1: proto.linkageGetResp
	(*LinkageInfo)(nil),     // 2: proto.linkageInfo
	(*LinkagePostReq)(nil),  // 3: proto.linkagePostReq
	(*LinkagePostResp)(nil), // 4: proto.linkagePostResp
	(*LinkageDelReq)(nil),   // 5: proto.linkageDelReq
	(*LinkageDelResp)(nil),  // 6: proto.linkageDelResp
	(*LinkagePutReq)(nil),   // 7: proto.linkagePutReq
	(*LinkagePutResp)(nil),  // 8: proto.linkagePutResp
}
var file_linkage_proto_depIdxs = []int32{
	2, // 0: proto.linkageGetResp.data:type_name -> proto.linkageInfo
	0, // 1: proto.Linkage.linkageGet:input_type -> proto.linkageGetReq
	3, // 2: proto.Linkage.linkagePost:input_type -> proto.linkagePostReq
	5, // 3: proto.Linkage.linkageDel:input_type -> proto.linkageDelReq
	7, // 4: proto.Linkage.linkagePut:input_type -> proto.linkagePutReq
	1, // 5: proto.Linkage.linkageGet:output_type -> proto.linkageGetResp
	4, // 6: proto.Linkage.linkagePost:output_type -> proto.linkagePostResp
	6, // 7: proto.Linkage.linkageDel:output_type -> proto.linkageDelResp
	8, // 8: proto.Linkage.linkagePut:output_type -> proto.linkagePutResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_linkage_proto_init() }
func file_linkage_proto_init() {
	if File_linkage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkageGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkageGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkagePostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkagePostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkageDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkageDelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkagePutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkagePutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkage_proto_goTypes,
		DependencyIndexes: file_linkage_proto_depIdxs,
		MessageInfos:      file_linkage_proto_msgTypes,
	}.Build()
	File_linkage_proto = out.File
	file_linkage_proto_rawDesc = nil
	file_linkage_proto_goTypes = nil
	file_linkage_proto_depIdxs = nil
}
